cache:
  paths:
    - 42sh

build_job:
  stage: build
  script:
    - apk add build-base && apk add make && apk add meson && apk add ninja
    - make build

test-parser:
  stage: test
  needs: [build_job]
  script:
    - ./tests/parser.sh
