variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - .cache/
  - venv/
  - 42sh
  - builddir/

before_script:
  - apk add build-base && apk add make && apk add meson && apk add ninja && apk add py3-pip && apk add dash
  - make build
  - pip3 install pyyaml

echo_builtin:
  stage: test
  script:
    - python3 tests/moulinette.py --binary 42sh --tests tests/echo.yml

command_list:
  stage: test
  script:
    - python3 tests/moulinette.py --binary 42sh --tests tests/command_list.yml

reserved_words:
  stage: test
  script:
    - python3 tests/moulinette.py --binary 42sh --tests tests/reserved_words.yml

cd:
  stage: test
  script:
    - python3 tests/moulinette.py --binary 42sh --tests tests/cd.yml
